### ISSUE TITLE
Couldn't load plugin 'pca4cd' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by darrensterling** [SMByC/PCA4CD#12]
After installing the PCA4CD plugin I get this error.  I've tried on two separate machines running both the latest stable, and the latest version of QGIS

Couldn't load plugin 'pca4cd' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pyqtgraph' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\__init__.py", line 87, in classFactory
    from .pca4cd import PCA4CD
  File "C:\PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\pca4cd.py", line 35, in 
    from pca4cd.gui.pca4cd_dialog import PCA4CDDialog
  File "C:\PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\pca4cd_dialog.py", line 37, in 
    from pca4cd.gui.main_analysis_dialog import MainAnalysisDialog
  File "C:\PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\main_analysis_dialog.py", line 37, in 
    from pca4cd.gui.layer_view_widget import LayerViewWidget
  File "C:\PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\layer_view_widget.py", line 30, in 
    from pca4cd.gui.component_analysis_dialog import ComponentAnalysisDialog
  File "C:\PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\component_analysis_dialog.py", line 152, in 
    FORM_CLASS, _ = uic.loadUiType(Path(plugin_folder, 'ui', 'component_analysis_dialog.ui'))
  File "C:\PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS32~1.16\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 377, in 
  File "C:\PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyqtgraph'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.16-Białowieża Białowieża, 6f08e4d7 

Python Path:
C:/PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python
C:/Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.16/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.16\bin\python39.zip
C:\PROGRA~1\QGIS32~1.16\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.16\apps\Python39\lib
C:\Program Files\QGIS 3.22.16\bin
C:\PROGRA~1\QGIS32~1.16\apps\Python39
C:\PROGRA~1\QGIS32~1.16\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.16\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.16\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.16\apps\Python39\lib\site-packages\Pythonwin
C:/Users/sabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by XavierCLL** [comment]
Hi @darrensterling 

Have you tried the zip all-in-one? https://github.com/SMByC/PCA4CD#package-all-in-one---windows-64bits

Maybe that isn't very clear for some users and I'm going to include the libs required by the plugin inside the package in the Qgis plugin repository

**Comment by darrensterling** [comment]
Yup, that works.  Thanks.  (Trouble shooting for my daughter who's a GIS Uni student so the notion of missing libs is a bit opaque to her.)
