### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by EABsaeon** [SMByC/PCA4CD#13]

**Comment by XavierCLL** [comment]
Hi @EABsaeon 

Could you please copy/paste the full-text error and/or a screenshot? thanks

**Comment by EABsaeon** [comment]
Hi Xavier,

The full text, plus screen shot.

Traceback (most recent call last):

File
"C:\Users/Erika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py",
line 36, in wrapper

return func(*args, **kwargs)

File
"C:\Users/Erika/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\pca4cd_dialog.py",
line 216, in generate_principal_components

pca_files, pca_stats = pca(path_layer_A, path_layer_B, n_pc,
estimator_matrix, pca4cd.tmp_dir,

TypeError: cannot unpack non-iterable NoneType object






[image: image.png]


Also, I must download GEE Python in order to resolve the below error when
opening QGIS? I'm a bit confused by this because I use GEE online so then I
just must load Python on my machine? Thanks in advance.



[image: image.png]

Kind Regards,
Erika

*Erika Brown *
Marine Ecologist Spatial Analytics & GIS Specialist
MSc. Biological Oceanography
Tel +27 72 808 2933
Email ***@***.*** ***@***.***>

*“When one tugs at a single thing in nature, he finds it attached to the
rest of the world.”  *John Muir

**Comment by XavierCLL** [comment]
Hi @EABsaeon,

You are replying to me using the GitHub conversation/issue system, and I think it's not allowed to attach images in that way, and without screenshots is very difficult to understand what is happening, could you please send me again directly to my email: xavier.corredor.llano@gmail.com ? also could you send me (only if possible)  the image that you are processing the PCA?. The same for the question about GEE.

Regards,
Xavier

**Comment by ayush7ad6** [comment]
Hi @XavierCLL @EABsaeon ,
Could you share the solution for it?
I'm facing the same issue.

**Comment by XavierCLL** [comment]
Hi @EABsaeon,

I didn't fix it because I couldn't reproduce the issue, is it possible you can share your layer to try to reproduce the same the problem?

**Comment by ghost** [comment]
I have had the same issue - I would like to resolve it. 

"Traceback (most recent call last):
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\pca4cd_dialog.py", line 216, in generate_principal_components
    pca_files, pca_stats = pca(path_layer_A, path_layer_B, n_pc, estimator_matrix, pca4cd.tmp_dir,
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
"

**Comment by XavierCLL** [comment]
Hi @lauren81 

The error is because there are some issue computing the PCA specific for your data (most of the cases) if you can share a small section of your data where you can get the same error, I can check the issue.
