### ISSUE TITLE
PCA4CD dá erro quando rodo

### ISSUE THREAD

**Issue by HelderJardim** [SMByC/PCA4CD#15]
PCA4CD está dando erro quando rodo e não calcula as PCA's. Este é o texto que aparece como erro:
Traceback (most recent call last):
  File "C:\Users/HelderJardim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "C:\Users/HelderJardim/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\pca4cd_dialog.py", line 216, in generate_principal_components
    pca_files, pca_stats = pca(path_layer_A, path_layer_B, n_pc, estimator_matrix, pca4cd.tmp_dir,
TypeError: cannot unpack non-iterable NoneType object
![image](https://github.com/user-attachments/assets/5062f866-c5f0-4943-8c11-d432897ad171)

**Comment by HelderJardim** [comment]
![image](https://github.com/user-attachments/assets/6ccb8c43-0dbe-4fb1-bce9-e550fd374964)

**Comment by XavierCLL** [comment]
Hi @HelderJardim thanks for reporting the error, english (or spanish) please.

That error seems that something happened in the PCA almost sure it is a data issue, could you share your raster (or small part of it)? To reproduce the error locally. (I think you closed it by error?)

**Comment by HelderJardim** [comment]
Do you want me to send the image? It is a Landsat 9 image (LC09_L2SP_218074_20241002_20241003_02_T1)

**Comment by XavierCLL** [comment]
I'm almost sure that is due that one band in that stack is empty (with nodata or zeros), compute a PCA in that situation is impossible, so check your data carefully

**Comment by HelderJardim** [comment]
Sorry for my English. It's not very good. But when I calculated the mosaic histogram, all the bands appear, as shown in the figure.
![image](https://github.com/user-attachments/assets/b8de42fc-ea9d-4e87-8a5c-6007cf812b62)

**Comment by HelderJardim** [comment]
![image](https://github.com/user-attachments/assets/2f6aa4fa-60fd-46ce-953e-85a06300fc6f)

**Comment by XavierCLL** [comment]
Ok, then the error could be due to another reason, I don't have time to download it, could you clip it in a small area and send it to me please? The only way to understand what is happening is reproducing the error locally.

**Comment by XavierCLL** [comment]
Hi, there is a high probability that this bug is fixed with the new version: https://github.com/SMByC/PCA4CD/releases/tag/26.5, closing for now, but open it if the bug persists
