### ISSUE TITLE
"[WinError 2] The system cannot find the file specified"

### ISSUE THREAD

**Issue by indrarangga18** [SMByC/PCA4CD#7]
Hi PCA4CD team,

I got an issue "[WinError 2] The system cannot find the file specified", can you help me to solve this problem ?

Im already used QGIS 3.12.1

here's the error code:
Traceback (most recent call last):
  File "C:/Users/IndraR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "C:/Users/IndraR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 86, in wrapper
    obj_returned = func(*args, **kwargs)
  File "C:/Users/IndraR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\main_analysis_dialog.py", line 277, in save
    subprocess.run(cmd)
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Thank You
Best Regards

**Comment by XavierCLL** [comment]
Hi, thanks for the report!

in which part of the process did you receive this error?

**Comment by indrarangga18** [comment]
Hi,
Thanks for the response.

I got this error message after input stack layer based on my research CRS. After PCA layer show 7 layer i already input in stack then i click save as PCA. From this button i got the error message.

Thank You

**Comment by indrarangga18** [comment]
any update regarding this ?

**Comment by XavierCLL** [comment]
I was trying to reproduce the error, I already could! working on it...

**Comment by XavierCLL** [comment]
Fixed with commits af201d9b0ed7aa52a4f9a7d298e75a8b98a27a74 and 277b47f0eb3aff491ac55ede697067fefa114aea

Please confirm it updating the plugin to v20.4.20 and testing it, thanks

**Comment by indrarangga18** [comment]
Sorry late report, its works , great !
Many Thanks !

**Comment by indrarangga18** [comment]
I update the vesion
